services:

  web:

    image: ${DOCKER_USER}/travel-app:v${TAG}

    restart: unless-stopped
    
    ports:
      - "8090:80"

    depends_on:
      - db

    env_file:
      - .env

    environment:
      DB_HOST: db

    networks:
      - travel-network


  db:

    image: postgres:16

    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - travel-network


volumes:

  postgres_data:


networks:

  travel-network:
    driver: bridge
